### ISSUE TITLE
Feature Request | 2 useful features

### ISSUE THREAD

**Issue by ez-art** [Clientastisch/Cardinal-Anticheat#107]
**What features would you like added? Describe them here**
1- add /cac reset (player) ____ to reset vl of player
2- add %check% and %type% veriables
For example:
```
command:
     tempban: tempban %player% Hacking %check% 
     permban: ban %player% Hacking %check% %type%
```

i think this so useful for anyone !

**Comment by Clientastisch** [comment]
Thank you for your suggestions.
First of all, a reset of violation levels isn't necessary because CAC doesn't use global violation levels and each check has a certain time value till the violation disappears. This can be configurated in for each check. 
Secoundly, I added the requested reason option for bans which can be accessed using %reason% in version higher than 0.9982
