### ISSUE TITLE
Feature Request | Plugin messages

### ISSUE THREAD

**Issue by iJosePlay** [Clientastisch/Cardinal-Anticheat#117]
What features would you like added? Describe them here
Hi, could you add a messages.yml to modify some plugin messages?

**Comment by Clientastisch** [comment]
That is a feature that has been requested quiet a lot and also been rejected every time.
I do not see why an admin should be able to change the prefix or messages of an anticheat because it's not visibile for normal players. Being able to change the plugin prefix or messages kinda steals identity. That's the least credit a developer should earn for his work
