### ISSUE TITLE
Bug Report | 

### ISSUE THREAD

**Issue by rangedwolf** [Clientastisch/Cardinal-Anticheat#153]
What type of bug you want to report? Describe it here
it sead i was banned i try to join and i can

When does the bug occurr?
very time i hack on the server 

Cardinal Version:
1.8
Spigot Version:
1.8.8

> **Attached Files  (Required)**
[New WinRAR ZIP archive (2).zip](https://github.com/Clientastisch/Cardinal-Anticheat/files/6670444/New.WinRAR.ZIP.archive.2.zip)

**Comment by Clientastisch** [comment]
Everything works fine, it's just that you haven't read the documentation.
Cardinal doesn't use an own database but a system called [Dialects](https://github.com/Clientastisch/Cardinal-Anticheat/blob/master/DIALECT.md). 
There are already different types available and you can make your own!

- [MySQL](https://github.com/Clientastisch/Cardinal-Anticheat/raw/master/dialects/MariaDialect.jar)
- [MongoDB](https://github.com/Clientastisch/Cardinal-Anticheat/raw/master/dialects/MongoDialect.jar)

_Creating your own dialect secures the data usage and guarantees the protection of sensitive data, since Cardinal has neither access to the connection nor to any credentials which are typically required. In addition, this gives you the opportunity to migrate to any form of database you desire._
